//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosProveedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alimento()
        {
            this.DetalleAlimento = new HashSet<DetalleAlimento>();
        }
    
        public decimal Codigo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fecha_elaboracion { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public decimal stock { get; set; }
        public decimal Sucursal { get; set; }
        public decimal activo { get; set; }
        public decimal TipoAlimento { get; set; }
        public decimal CategoriaAlimento { get; set; }
        public string foto { get; set; }
    
        public virtual Sucursal Sucursal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleAlimento> DetalleAlimento { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual TipoAlimento TipoAlimento1 { get; set; }
    }
}
