//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosProveedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosBancarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatosBancarios()
        {
            this.Saldo = new HashSet<Saldo>();
        }
    
        public decimal codigo { get; set; }
        public decimal numeroCuenta { get; set; }
        public decimal Banco { get; set; }
        public decimal TipoCuenta { get; set; }
        public decimal Sucursal { get; set; }
        public decimal activo { get; set; }
    
        public virtual Banco Banco1 { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        public virtual TipoCuenta TipoCuenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saldo> Saldo { get; set; }
    }
}
