//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosProveedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldo
    {
        public decimal codigo { get; set; }
        public decimal datosBancarios { get; set; }
        public decimal monto { get; set; }
    
        public virtual DatosBancarios DatosBancarios1 { get; set; }
    }
}
