//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mbbCementerioEntities : DbContext
    {
        public mbbCementerioEntities()
            : base("name=mbbCementerioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<dato_interes> dato_interes { get; set; }
        public virtual DbSet<detalle_dato_interes> detalle_dato_interes { get; set; }
        public virtual DbSet<detalle_factura> detalle_factura { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<fallecido> fallecido { get; set; }
        public virtual DbSet<familiar> familiar { get; set; }
        public virtual DbSet<jornada_laboral> jornada_laboral { get; set; }
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<sector> sector { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_tumba> tipo_tumba { get; set; }
        public virtual DbSet<tumba> tumba { get; set; }
    }
}
