//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_dato_interes
    {
        public int id { get; set; }
        public int familiar_id { get; set; }
        public int dato_interes_id { get; set; }
    
        public virtual dato_interes dato_interes { get; set; }
        public virtual familiar familiar { get; set; }
    }
}
