//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_factura()
        {
            this.factura = new HashSet<factura>();
        }
    
        public int id { get; set; }
        public int tumba_id { get; set; }
        public int sector_id { get; set; }
        public int familiar_id { get; set; }
        public int fallecido_id { get; set; }
    
        public virtual fallecido fallecido { get; set; }
        public virtual familiar familiar { get; set; }
        public virtual sector sector { get; set; }
        public virtual tumba tumba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
    }
}
